package com.daeeun.sohnori.myclass;

public class RemsProtocol {
	public final static String faultNormal = "정상";
	public final static String faultEtc = "기타에러";
	public final static String faultEarth = "지락(누전)";
	public final static String faultStandAlone = "지락(누전)";
	public final static String faultUF = "계통 저주파수";
	public final static String faultOF = "계통 과주파수";
	public final static String faultOC = "계통 과전류";
	public final static String faultUV = "계통 저전압";
	public final static String faultOV = "계통 과전압";
	public final static String faultOH = "과열";
	public final static String faultIGBT = "IGBT에러";
	public final static String faultPVOC = "PV과전류";
	public final static String faultPVUV = "PV저전압";
	public final static String faultPVOV = "PV과전압";
	public final static String statusRun = "RUN";
	public final static String statusStop = "STOP";
	public RemsProtocol() {
		
	}
	public static String getResult(String packet) {
		StringBuilder retStr = new StringBuilder();
		String str;
		int energy;
		int type;
		int data;
		str = packet.substring(0, 2);		
		if(str.equals("14")!=true) return null;
		if(packet.length()<10) return null;
		retStr.append("패킷: REMS 프로토콜\r\n");
		retStr.append("에너지원: ");
		str = packet.substring(2, 4);
		energy = Integer.parseInt(str, 16);
		str = packet.substring(4, 6);
		type = Integer.parseInt(str, 16);
		if(energy==1 && type==1) retStr.append("태양광 단상\r\n");
		else if(energy==1 && type==2) retStr.append("태양광 삼상\r\n");
		else if(energy==2 && type==1) retStr.append("태양열 강제순환식\r\n");
		else if(energy==2 && type==2) retStr.append("태양열 자연순환식\r\n");
		else if(energy==3 && type==1) retStr.append("지열 히트펌프\r\n");
		else if(energy==3 && type==2) retStr.append("지열 부하측\r\n");
		else if(energy==4) retStr.append("풍력\r\n");
		else if(energy==6) retStr.append("연료전지\r\n");
		else if(energy==7) retStr.append("ESS\r\n");
		else retStr.append("알수없음-"+energy+" "+type+"\r\n");
		str = packet.substring(8, 10);
		retStr.append("패킷에러코드: ");
		if(str.equals("38")) {
			retStr.append("시리얼포트 열기실패");
			return retStr.toString();
		}
		else if(str.equals("39")) {
			retStr.append("시리얼 통신실패");
			return retStr.toString();
		}
		else retStr.append("정상\r\n");
		if(energy==1 && type==1) {
			retStr.append("PV전압: ");
			str = packet.substring(10, 14);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" V\r\n");
			retStr.append("PV전류: ");
			str = packet.substring(14, 18);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" A\r\n");
			retStr.append("PV전력: ");
			str = packet.substring(18, 22);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" W\r\n");
			retStr.append("Grid전압: ");
			str = packet.substring(22, 26);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" V\r\n");
			retStr.append("Grid전류: ");
			str = packet.substring(26, 30);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" A\r\n");
			retStr.append("Grid전력: ");
			str = packet.substring(30, 34);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" W\r\n");
			retStr.append("역률: ");
			str = packet.substring(34, 38);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+"\r\n");
			retStr.append("주파수: ");
			str = packet.substring(38, 42);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" Hz\r\n");
			retStr.append("누적발전량: ");
			str = packet.substring(42, 58);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" Wh\r\n");
			retStr.append("고장여부: ");
			str = packet.substring(58, 62);
			data = Integer.parseInt(str, 16);
			if(data==0 || data==1) retStr.append(faultNormal+"\r\n");					
			else if((data&0b0000000000000010)>0) retStr.append(faultPVOV+"\r\n");
			else if((data&0b0000000000000100)>0) retStr.append(faultPVUV+"\r\n");
			else if((data&0b0000000000001000)>0) retStr.append(faultPVOC+"\r\n");
			else if((data&0b0000000000010000)>0) retStr.append(faultIGBT+"\r\n");
			else if((data&0b0000000000100000)>0) retStr.append(faultOH+"\r\n");
			else if((data&0b0000000001000000)>0) retStr.append(faultOV+"\r\n");
			else if((data&0b0000000010000000)>0) retStr.append(faultUV+"\r\n");
			else if((data&0b0000000100000000)>0) retStr.append(faultOC+"\r\n");
			else if((data&0b0000001000000000)>0) retStr.append(faultOF+"\r\n");
			else if((data&0b0000010000000000)>0) retStr.append(faultUF+"\r\n");
			else if((data&0b0000100000000000)>0) retStr.append(faultStandAlone+"\r\n");
			else if((data&0b0001000000000000)>0) retStr.append(faultEarth+"\r\n");			
			else retStr.append("\r\n");
			retStr.append("동작유무: ");			
			if((data&0b0000000000000001)>0) retStr.append(statusStop+"\r\n");
			else retStr.append(statusRun+"\r\n");
		}
		else if(energy==1 && type==2) {
			retStr.append("PV전압: ");
			str = packet.substring(10, 14);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" V\r\n");
			retStr.append("PV전류: ");
			str = packet.substring(14, 18);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" A\r\n");
			retStr.append("PV전력: ");
			str = packet.substring(18, 26);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" W\r\n");
			retStr.append("Grid R전압: ");
			str = packet.substring(26, 30);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" V\r\n");
			retStr.append("Grid S전압: ");
			str = packet.substring(30, 34);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" V\r\n");
			retStr.append("Grid T전압: ");
			str = packet.substring(34, 38);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" V\r\n");
			retStr.append("Grid R전류: ");
			str = packet.substring(38, 42);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" A\r\n");
			retStr.append("Grid S전류: ");
			str = packet.substring(42, 46);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" A\r\n");
			retStr.append("Grid T전류: ");
			str = packet.substring(46, 50);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" A\r\n");
			retStr.append("Grid전력: ");
			str = packet.substring(50, 58);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" W\r\n");
			retStr.append("역률: ");
			str = packet.substring(58, 62);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+"\r\n");
			retStr.append("주파수: ");
			str = packet.substring(62, 66);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" Hz\r\n");
			retStr.append("누적발전량: ");
			str = packet.substring(66, 82);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" Wh\r\n");
			retStr.append("고장여부: ");
			str = packet.substring(82, 86);
			data = Integer.parseInt(str, 16);
			if(data==0 || data==1) retStr.append(faultNormal+"\r\n");					
			else if((data&0b0000000000000010)>0) retStr.append(faultPVOV+"\r\n");
			else if((data&0b0000000000000100)>0) retStr.append(faultPVUV+"\r\n");
			else if((data&0b0000000000001000)>0) retStr.append(faultPVOC+"\r\n");
			else if((data&0b0000000000010000)>0) retStr.append(faultIGBT+"\r\n");
			else if((data&0b0000000000100000)>0) retStr.append(faultOH+"\r\n");
			else if((data&0b0000000001000000)>0) retStr.append(faultOV+"\r\n");
			else if((data&0b0000000010000000)>0) retStr.append(faultUV+"\r\n");
			else if((data&0b0000000100000000)>0) retStr.append(faultOC+"\r\n");
			else if((data&0b0000001000000000)>0) retStr.append(faultOF+"\r\n");
			else if((data&0b0000010000000000)>0) retStr.append(faultUF+"\r\n");
			else if((data&0b0000100000000000)>0) retStr.append(faultStandAlone+"\r\n");
			else if((data&0b0001000000000000)>0) retStr.append(faultEarth+"\r\n");			
			else retStr.append("\r\n");
			retStr.append("동작유무: ");			
			if((data&0b0000000000000001)>0) retStr.append(statusStop+"\r\n");
			else retStr.append(statusRun+"\r\n");
		}
		else if(energy==2 && type==1) {
			retStr.append("집열기 입구온도: ");
			str = packet.substring(10, 14);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("집열기 출구온도: ");
			str = packet.substring(14, 18);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("축열조 상부온도: ");
			str = packet.substring(18, 22);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("축열조 하부온도: ");
			str = packet.substring(22, 24);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("유량값: ");
			str = packet.substring(26, 34);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" LPM\r\n");
			retStr.append("누적생산량: ");
			str = packet.substring(34, 50);
			data = Integer.parseInt(str, 16);
			retStr.append(data/100+"."+data%100+" kcal\r\n");
			retStr.append("급수온도: ");
			str = packet.substring(50, 54);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("급탕온도: ");
			str = packet.substring(54, 58);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("소비유량값: ");
			str = packet.substring(58, 66);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" LPM\r\n");
			retStr.append("누적사용열량: ");
			str = packet.substring(66, 82);
			data = Integer.parseInt(str, 16);
			retStr.append(data/100+"."+data%100+" kcal\r\n");
			retStr.append("고장여부: ");
			str = packet.substring(82, 86);
			data = Integer.parseInt(str, 16);
			if(data==0) retStr.append("작동중\r\n");
			else if(data==1) retStr.append("미작동\r\n");			
		}
		else if(energy==2 && type==2) {
			retStr.append("급수배관온도: ");
			str = packet.substring(10, 14);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("급탕배관온도: ");
			str = packet.substring(14, 18);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("유량값: ");
			str = packet.substring(18, 26);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" LPM\r\n");
			retStr.append("누적사용량: ");
			str = packet.substring(26, 42);
			data = Integer.parseInt(str, 16);
			retStr.append(data/100+"."+data%100+" kcal\r\n");
			retStr.append("고장여부: ");
			str = packet.substring(42, 46);
			data = Integer.parseInt(str, 16);
			if(data==0) retStr.append("작동중\r\n");
			else if(data==1) retStr.append("미작동\r\n");
			
		}
		else if(energy==3 && type==1) {
			retStr.append("전압: ");
			str = packet.substring(10, 14);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" V\r\n");
			retStr.append("전류: ");
			str = packet.substring(14, 18);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" A\r\n");
			retStr.append("출력: ");
			str = packet.substring(18, 22);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" W\r\n");
			retStr.append("히트펌프 열생산량: ");
			str = packet.substring(22, 30);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" W\r\n");
			retStr.append("히트펌프 누적생산량: ");
			str = packet.substring(30, 46);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" kWh\r\n");
			retStr.append("히트펌프 누적전력사용량: ");
			str = packet.substring(46, 62);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" kWh\r\n");
			retStr.append("히트펌프 상태값: ");
			str = packet.substring(62, 64);
			data = Integer.parseInt(str, 16);
			if(data==0) retStr.append("미작동\r\n");
			else if(data==1) retStr.append("냉방\r\n");
			else if(data==2) retStr.append("난방\r\n");
			retStr.append("히트펌프 지열수 입구온도: ");
			str = packet.substring(64, 70);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("히트펌프 지열수 출구온도: ");
			str = packet.substring(70, 74);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("히트펌프 냉난방 입구온도: ");
			str = packet.substring(74, 78);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("히트펌프 냉난방 출구온도: ");
			str = packet.substring(78, 82);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("히트펌프 냉온수 유량: ");
			str = packet.substring(82, 90);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" LPM\r\n");
			retStr.append("고장여부: ");
			str = packet.substring(90, 94);
			data = Integer.parseInt(str, 16);
			if(data==0) retStr.append("작동중\r\n");
			else if(data==1) retStr.append("미작동\r\n");
		}
		else if(energy==3 && type==2) {
			retStr.append("냉난방측 입구온도: ");
			str = packet.substring(10, 14);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("냉난방측 출구온도: ");
			str = packet.substring(14, 18);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("냉난방측 사용유량값: ");
			str = packet.substring(18, 26);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" LPM\r\n");
			retStr.append("냉난방측 누적사용열량: ");
			str = packet.substring(26, 42);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" kWh\r\n");
			retStr.append("급탕측 급수온도: ");
			str = packet.substring(42, 46);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("급탕측 급탕온도: ");
			str = packet.substring(46, 50);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("급탕측 사용유량값: ");
			str = packet.substring(50, 58);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" LPM\r\n");
			retStr.append("급탕측 누적사용열량: ");
			str = packet.substring(58, 74);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" kWh\r\n");			
			retStr.append("고장여부: ");
			str = packet.substring(74, 78);
			data = Integer.parseInt(str, 16);
			if(data==0) retStr.append("작동중\r\n");
			else if(data==1) retStr.append("미작동\r\n");
		}
		else if(energy==4) {
			retStr.append("(전)전압: ");
			str = packet.substring(10, 14);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" V\r\n");
			retStr.append("(전)전류: ");
			str = packet.substring(14, 18);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" A\r\n");
			retStr.append("(전)출력: ");
			str = packet.substring(18, 22);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" W\r\n");
			retStr.append("(후)전압: ");
			str = packet.substring(22, 26);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" V\r\n");
			retStr.append("(후)전류: ");
			str = packet.substring(26, 30);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" A\r\n");
			retStr.append("(후)출력: ");
			str = packet.substring(30, 34);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" W\r\n");
			retStr.append("주파수: ");
			str = packet.substring(34, 38);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" Hz\r\n");
			retStr.append("누적발전량: ");
			str = packet.substring(38, 54);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" Wh\r\n");
			retStr.append("고장여부: ");
			str = packet.substring(54, 58);
			data = Integer.parseInt(str, 16);
			if(data==0) retStr.append("작동중\r\n");
			else if(data==1) retStr.append("미작동\r\n");
			
		}
		else if(energy==6) {
			retStr.append("(전)전압: ");
			str = packet.substring(10, 14);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" V\r\n");
			retStr.append("(전)전류: ");
			str = packet.substring(14, 18);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" A\r\n");
			retStr.append("(전)출력: ");
			str = packet.substring(18, 22);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" W\r\n");
			retStr.append("(후)전압: ");
			str = packet.substring(22, 26);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" V\r\n");
			retStr.append("(후)전류: ");
			str = packet.substring(26, 30);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" A\r\n");
			retStr.append("(후)출력: ");
			str = packet.substring(30, 34);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" W\r\n");
			retStr.append("연료전지 열생산열량: ");
			str = packet.substring(34, 38);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" W\r\n");
			retStr.append("연료전지 누적생산열량: ");
			str = packet.substring(38, 54);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" kWh\r\n");
			retStr.append("누적사용열량: ");
			str = packet.substring(54, 70);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" kWh\r\n");
			retStr.append("전일 누적사용열량: ");
			str = packet.substring(70, 86);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" kWh\r\n");
			retStr.append("연료전지 급수온도: ");
			str = packet.substring(86, 90);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("연료전지 출수온도: ");
			str = packet.substring(90, 94);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("역률: ");
			str = packet.substring(94, 98);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" %\r\n");
			retStr.append("주파수: ");
			str = packet.substring(98, 102);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" Hz\r\n");
			retStr.append("누적발전량: ");
			str = packet.substring(102, 118);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" Wh\r\n");
			retStr.append("고장여부: ");
			str = packet.substring(118, 122);
			data = Integer.parseInt(str, 16);
			if(data==0) retStr.append("작동중\r\n");
			else if(data==1) retStr.append("미작동\r\n");
		}
		else if(energy==7) {
			retStr.append("(전)전압: ");
			str = packet.substring(10, 14);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" V\r\n");
			retStr.append("(전)전류: ");
			str = packet.substring(14, 18);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" A\r\n");
			retStr.append("(전)출력: ");
			str = packet.substring(18, 22);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" W\r\n");
			retStr.append("(후)전압: ");
			str = packet.substring(22, 26);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" V\r\n");
			retStr.append("(후)전류: ");
			str = packet.substring(26, 30);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" A\r\n");
			retStr.append("(후)출력: ");
			str = packet.substring(30, 34);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" W\r\n");
			retStr.append("배터리 상태: ");
			str = packet.substring(34, 36);
			data = Integer.parseInt(str, 16);
			if(data==0) retStr.append("미동작\r\n");
			else if(data==1) retStr.append("충전중\r\n");
			retStr.append("배터리 SOC: ");
			str = packet.substring(36, 38);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" %\r\n");
			retStr.append("베터리 SOH: ");
			str = packet.substring(38, 40);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" %\r\n");
			retStr.append("배터리온도(최저): ");
			str = packet.substring(40, 44);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("배터리온도(최고): ");
			str = packet.substring(44, 48);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("배터리온도(평균): ");
			str = packet.substring(48, 52);
			data = Integer.parseInt(str, 16);
			retStr.append(data/10+"."+data%10+" 도\r\n");
			retStr.append("배터리전압: ");
			str = packet.substring(52, 56);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" V\r\n");
			retStr.append("배터리전류: ");
			str = packet.substring(56, 60);
			data = Integer.parseInt(str, 16);
			retStr.append(data+" A\r\n");
			retStr.append("고장여부: ");
			str = packet.substring(60, 64);
			data = Integer.parseInt(str, 16);
			if(data==0) retStr.append("작동중\r\n");
			else if(data==1) retStr.append("미작동\r\n");
		}
		return retStr.toString();
	}
}
